---
- name: httpd install
  yum: name=httpd state=latest

- name: "httpd.conf setting"
  template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf

- name: start
  service: name=httpd state=started enabled=yes
